# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GD-Graph-smoothlines
version:      1.5
version_from: 
installdirs:  site
requires:
    GD:                            2.35
    GD::Graph:                     1.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
